version: 0.2
phases: 
  install: 
    runtime-versions: 
      java: corretto11
  pre_build:
    on-failure: ABORT
    commands:
      - echo Checking java version/installation
      - java -version
      - echo Checking maven version/installation
      - mvn -version
      - echo In the pre_build phase...
      - mvn -f ./snowbunnies -DskipTests clean install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - mvn -f ./snowbunnies -DskipTests package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'target/*.jar'
  base-directory: snowbunnies
